import { Lato } from 'next/font/google';
import './globals.css';
import StoreProvider from './provider';

const lato = Lato({ weight: ['400'], subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={lato.className}>{children}</body>
      </html>
    </StoreProvider>
  );
}
